### ISSUE TITLE
Invalid value for option "components": expected an Object, but got Array.

### ISSUE THREAD

**Issue by DannnB** [EvanAgee/vuejs-wordpress-theme-starter#4]
@EvanAgee Any way of sorting out this issue temporally till Bootstrap Vue beta.10 is out?

Think it might be messing with the `<router-view></router-view>` as nothing is showing.

[Bootstrap-Vue Issue #1201](https://github.com/bootstrap-vue/bootstrap-vue/issues/1201)

![image](https://user-images.githubusercontent.com/7425880/32171794-43486b1e-bd71-11e7-9a06-ce098aa8085f.png)

Thanks

**Comment by EvanAgee** [comment]
Hey @DannnB you mind showing me some of your component code so I can see what's up?

**Comment by FabriPalladino** [comment]
Hi, I just cloned the repository and I have the same issue, at the first npm run watch command...

thnak's for you help and contributions!

**Comment by EvanAgee** [comment]
Looking into it now

**Comment by EvanAgee** [comment]
I've pushed an update. You'll want to delete your node_modules directory and run `npm install` or `yarn install` again. Let me know if that works for you guys until they update Bootstrap-Vue. Thanks for reporting!

**Comment by EvanAgee** [comment]
Also if you guys are interested in joining the Vue Wordpress slack community shoot me your email addresses to evanagee-at-gmail.com and I'll send you an invite.

**Comment by DannnB** [comment]
@EvanAgee Hey, 
Sure I'll join,will send an email later! Thanks.

Deleted the node_modules folder but now getting this mismatch. I guess I could work it out but you might be able to do it faster :)

```
Uncaught Error: Module build failed: Error: 

Vue packages version mismatch:

- vue@2.4.4
- vue-template-compiler@2.5.2

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-loader\lib\parser.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-loader\lib\loader.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-loader\index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-loader\lib\parser.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-loader\lib\loader.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\vue-wordpress\wp-content\themes\vuejs-wordpress-theme-starter\node_modules\vue-loader\index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Object../src/components/Home.vue (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/app.js:3441:7)
    at __webpack_require__ (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/manifest.js:55:30)
    at Object../src/router/index.js (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/app.js:3466:75)
    at __webpack_require__ (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/manifest.js:55:30)
    at Object../src/app.js (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/app.js:3348:66)
    at __webpack_require__ (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/manifest.js:55:30)
    at Object.0 (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/app.js:3961:1)
    at __webpack_require__ (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/manifest.js:55:30)
    at webpackJsonpCallback (http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/manifest.js:26:23)
    at http://localhost/vue-wordpress/wp-content/themes/vuejs-wordpress-theme-starter/dist/scripts/app.js:1:1
```

Sorry the `<router-view>` is my fault, I don't set up virtual hosts at work or home so it was looking for all the app stuff at localhost/ and not localhost/vue-wordpress.

My fix (i'm only starting with webpack and vuejs sort of frameworks):
```
{
      path: '/vue-wordpress/',
      name: 'Home',
      component: Home,
      // props: { pageContentID: 383 }
    },
    {
      path: '/vue-wordpress/posts',
      name: 'Posts',
      component: Posts
    },
    {
      path: '/vue-wordpress/profile',
      name: 'Profile',
      component: Profile
    }
```

**Comment by FabriPalladino** [comment]
@DannnB are you installing using **npm**? cause for me **yarn install** worked well..

Thank you @EvanAgee, I send you the mail to join.

Have a nice day

**Comment by DannnB** [comment]
@FabriPalladino Hmm I was using the wrong command! `npm run dev` 
`npm run watch` works

Also install yarn to test and all is good! Thanks for that. Now time to learn why use yarn and not npm aha

Issue closed I think?

**Comment by EvanAgee** [comment]
Haha I'm still getting used to using Yarn myself ;) I think we can close this one for now. Any feature requests? I've been mulling over a few ideas but I'm trying to ride the line between keeping this a starter theme and wanting to add more features. Thoughts??

**Comment by DannnB** [comment]
@EvanAgee Leave it a starter theme. Though there could always be a full feature/example branch of what can be done with vue and the api. 
Even User profiles (Firebase/Wordpress users), route restricting to auth 'd users and have some public pages for none logged in users. 
But yeah leave all that to Slack I guess! Bit too far for this theme branch :)
